version: '3.8'

services:
  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: testdb
    ports:
      - "3307:3306"
    restart: always

  webapp:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    restart: always
